// 1. Founder dependency diagnostic
const bottlenecks=[
  {id:'sales',name:'Founder-held sales knowledge',title:'Transfer the founder sales narrative first',diagnosis:'Your strongest sales language, objection handling and commercial judgement still work best when you are personally involved. Growth is difficult to transfer without a drop in quality.',metric:'A capable team member can run a qualified discovery call and explain the value without founder preparation or rescue.',actions:['Review three recent sales calls and mark the moments that changed the prospect’s understanding.','Write a one-page founder sales narrative using the language, examples, objections and proof from those calls.','Have another person use it in a real or simulated conversation, then record where quality still drops.']},
  {id:'positioning',name:'Unclear positioning',title:'Make the customer and problem unmistakable',diagnosis:'The company is too difficult to recognise, remember or refer because the message is broad, inconsistent or product-led.',metric:'A best-fit buyer can accurately explain who the product is for and why it matters after seeing the opening message briefly.',actions:['Review the last ten wins and identify the repeated buyer, trigger, problem and consequence.','Write one specific message naming the customer, problem and outcome.','Test it with five target buyers and keep it only if they understand it without explanation.']},
  {id:'pipeline',name:'Inconsistent pipeline',title:'Build one pipeline process that runs every week',diagnosis:'New business arrives in bursts because it depends on referrals, founder energy or occasional campaigns rather than a protected weekly process.',metric:'Qualified opportunities continue at an agreed weekly rate without a founder-led burst of activity.',actions:['Trace the source of the last ten qualified opportunities.','Choose the single channel with the strongest evidence and define a weekly activity target.','Run it for four uninterrupted weeks, changing only one variable at a time.']},
  {id:'proof',name:'Weak customer proof',title:'Turn customer outcomes into proof that sells',diagnosis:'Customer evidence is too vague, hidden or generic to help a sceptical prospect decide without founder explanation.',metric:'A salesperson can send one relevant proof asset that answers the prospect’s main doubt without founder explanation.',actions:['Interview three successful customers about their before state, trigger and measurable change.','Create one case study using problem, action, result and timeframe.','Organise proof by customer type, problem and objection.']},
  {id:'learning',name:'No commercial learning rhythm',title:'Install a weekly commercial learning loop',diagnosis:'The team is active, but evidence is not consistently reviewed, documented and used to change the next decision.',metric:'Every week ends with a documented decision, named owner, evidence target and one learning carried into the next cycle.',actions:['Run a commercial retrospective covering what worked, failed and changed your understanding.','Schedule a weekly 45-minute commercial decision meeting with a fixed agenda.','Create a simple experiment ledger and define the next test before launching it.']},
  {id:'hiring',name:'Unclear hiring foundation',title:'Clarify the system before making the senior hire',diagnosis:'A senior growth or marketing hire may be expected to resolve customer, positioning, channel and ownership questions that are not yet explicit.',metric:'A strong candidate can understand the context, priorities, decision rights and 90-day success measures before accepting the role.',actions:['Write the real GTM brief, including customer, positioning, working channels and constraints.','Define what must be true after 30, 60 and 90 days.','Confirm whether the real need is leadership, a specialist or additional execution capacity.']}
];
const bottleneckQuestions=[
  {b:0,c:'Sales knowledge',q:'Could another person run your next three discovery calls as effectively as you?',h:'Think about the nuance, examples and objection handling that make prospects understand the value.',o:[['No, it still depends on me','They would miss important context or judgement.',3],['Mostly, with a careful briefing','They could do it, but only after founder preparation.',2],['Yes, without me','The narrative is documented and reliably used.',1]]},
  {b:0,c:'Sales knowledge',q:'Who gives the clearest answer when a prospect asks why customers choose you?',h:'Choose the answer that reflects a normal sales conversation.',o:[['The founder, every time','The strongest explanation still lives with one person.',3],['Usually the founder','Others can cover parts, but quality varies.',2],['The team answers consistently','The explanation has been transferred and trained.',1]]},
  {b:1,c:'Positioning',q:'Can the team describe who you help and the outcome you deliver in one consistent sentence?',h:'A useful answer identifies a recognisable customer, problem and outcome.',o:[['No, it changes by person or prospect','The message is flexible enough to become vague.',3],['There is a version, but it is not sharp','The basics exist, but specificity is weak.',2],['Yes, it is specific and consistent','The same clear message is used across the company.',1]]},
  {b:1,c:'Positioning',q:'How quickly would a best-fit buyer know your website is meant for them?',h:'Imagine a sceptical prospect scanning the opening section for five seconds.',o:[['They probably would not','The language is broad, generic or product-led.',3],['After reading carefully','The buyer has to work for the meaning.',2],['Immediately','The opening names their situation and desired outcome.',1]]},
  {b:2,c:'Pipeline',q:'How predictable is qualified new-business pipeline from month to month?',h:'Judge qualified conversations and opportunities, not raw lead volume.',o:[['Highly variable','Strong months are followed by worrying gaps.',3],['Somewhat consistent','There is activity, but forecasting is unreliable.',2],['Predictable','A repeatable process creates a steady flow.',1]]},
  {b:2,c:'Pipeline',q:'How much pipeline comes from a process that runs without the founder being personally active?',h:'Consider whether it continues during busy delivery periods or founder absence.',o:[['Almost none','It relies on founder relationships or bursts of effort.',3],['Some, but not enough','Parts run independently, but founder activity still matters.',2],['Most of it','The team runs a documented weekly process.',1]]},
  {b:3,c:'Customer proof',q:'How convincing is your evidence of customer outcomes to a sceptical buyer?',h:'Specific before-and-after evidence is stronger than broad praise.',o:[['Weak','Mostly broad claims, logos or vague testimonials.',3],['Moderate','Some useful evidence exists, but it is inconsistent.',2],['Strong','Specific results are used throughout the buying journey.',1]]},
  {b:3,c:'Customer proof',q:'What can the team send when a prospect asks for proof?',h:'The best proof matches the buyer’s situation and likely objection.',o:[['A deck and broad testimonials','The founder still has to explain why it matters.',3],['One or two case studies','Useful, but not always specific enough.',2],['A relevant proof pack','Evidence is easy to match and send.',1]]},
  {b:4,c:'Learning rhythm',q:'Does the team have a weekly session for pipeline, experiments, evidence and commercial decisions?',h:'A useful rhythm creates decisions rather than simply reporting activity.',o:[['No, it is ad hoc','Commercial learning is easy to lose or delay.',3],['Sometimes','It is irregular or mostly a status update.',2],['Yes, every week','It produces clear decisions, owners and next tests.',1]]},
  {b:4,c:'Learning rhythm',q:'How often does the team test messaging, review results and record what it learned?',h:'Look for a loop where evidence changes what the team does next.',o:[['Rarely','Insights stay in individual heads and activity repeats.',3],['Occasionally','Testing starts mainly when performance drops.',2],['Regularly','Learning improves the next cycle.',1]]},
  {b:5,c:'Hiring foundation',q:'Are you planning to hire a senior marketing or growth leader in the next six months?',h:'This includes an active search or a likely near-term decision.',o:[['Yes, actively','The success of the hire depends on the foundation being ready.',3],['Possibly','The decision is live but not final.',2],['No, not soon','This is not a current dependency.',1]]},
  {b:5,c:'Hiring foundation',q:'If that person started tomorrow, how clear would their first 90 days be?',h:'Consider the customer, positioning, channels, targets, constraints and decision rights.',o:[['Unclear','They would need to discover what the role is meant to solve.',3],['Partly clear','Important context and measures are missing.',2],['Very clear','The brief, priorities and evidence targets are ready.',1]]}
];
function bottleneckIntro(){return introPage('bottleneck',{label:'Founder dependency diagnostic',title:TOOL_META.bottleneck.title,lead:'Find the commercial capability that still works mainly because the founder is involved, then decide what evidence would prove it has been transferred.',startFn:'startBottleneck',startLabel:completed('bottleneck')?'Review or retake':'Start the diagnosis',meta:'About 4 minutes · 12 questions · No artificial overall percentage',benefits:[['Find one dependency','The result names the strongest current signal, not a generic maturity score.'],['See the evidence','The diagnosis uses the actual answers that caused it.'],['Move into action','The result becomes an input to the Weekly Focus Planner.']]});}
window.startBottleneck=function(){
  session.tool='bottleneck';session.step=0;session.answers=(state.drafts.bottleneck?.answers||Array(bottleneckQuestions.length).fill(null));track('Tool Started',{tool:'bottleneck'});renderBottleneckStep();
};
window.chooseBottleneck=function(i){session.answers[session.step]=i;state.drafts.bottleneck={answers:session.answers};saveState();renderBottleneckStep();};
window.bottleneckNext=function(){if(session.answers[session.step]===null)return;if(session.step<bottleneckQuestions.length-1){session.step++;renderBottleneckStep();window.scrollTo(0,0);}else finishBottleneck();};
window.bottleneckBack=function(){if(session.step===0){session={};render();}else{session.step--;renderBottleneckStep();window.scrollTo(0,0);}};
function renderBottleneckStep(){
  const q=bottleneckQuestions[session.step];
  app.innerHTML=layout(`<div class="wizard">${progress(session.step,bottleneckQuestions.length,q.c)}<section class="panel"><span class="step-kicker">${esc(q.c)}</span><h2>${esc(q.q)}</h2><p class="intro">${esc(q.h)}</p><div class="options">${q.o.map((o,i)=>optionButton(o[0],o[1],i,session.answers[session.step]===i,'chooseBottleneck')).join('')}</div><div class="wizard-actions"><button class="back" onclick="bottleneckBack()">← ${session.step===0?'Start':'Back'}</button><button class="btn primary" onclick="bottleneckNext()" ${session.answers[session.step]===null?'disabled':''}>${session.step===bottleneckQuestions.length-1?'See my result':'Continue'} →</button></div></section></div>`,TOOL_META.bottleneck.title,TOOL_META.bottleneck.desc);
}
function finishBottleneck(){
  const scores=Array(bottlenecks.length).fill(0);
  session.answers.forEach((a,i)=>scores[bottleneckQuestions[i].b]+=bottleneckQuestions[i].o[a][2]);
  const ranked=scores.map((score,i)=>({score,i})).sort((a,b)=>b.score-a.score);const top=ranked[0],second=ranked[1];const data=bottlenecks[top.i];
  const gap=top.score-second.score;const conf=gap>=2&&top.score>=5?'strong':gap>=1?'medium':'low';
  const evidence=bottleneckQuestions.map((q,i)=>({q,a:q.o[session.answers[i]],idx:i})).filter(x=>x.q.b===top.i).map(x=>`${x.q.q} You selected “${x.a[0]}”: ${x.a[1]}`);
  const levels=scores.map(s=>s>=5?'High dependency':s>=4?'Mixed': 'Transferred');
  const result={id:data.id,label:data.name,title:data.title,diagnosis:data.diagnosis,confidence:conf,evidence,evidenceTarget:data.metric,actions:data.actions,scores,levels,createdAt:new Date().toISOString()};
  state.results.bottleneck=result;delete state.drafts.bottleneck;saveState();track('Tool Completed',{tool:'bottleneck',result:data.id});session={};render();
}
function bottleneckResult(){
  const r=state.results.bottleneck;if(!r)return bottleneckIntro();
  const copy=`FOUNDER DEPENDENCY DIAGNOSIS\n\nFocus first: ${r.label}\nConfidence: ${r.confidence}\n\nDiagnosis\n${r.diagnosis}\n\nEvidence from the assessment\n${r.evidence.map((x,i)=>`${i+1}. ${x}`).join('\n')}\n\nEvidence target\n${r.evidenceTarget}\n\nSuggested first moves\n${r.actions.map((x,i)=>`${i+1}. ${x}`).join('\n')}`;
  const stageRows=bottlenecks.map((b,i)=>{const level=r.levels[i];const cls=level==='High dependency'?'high':level==='Mixed'?'mixed':'good';return `<div class="stage-row"><strong>${esc(b.name)}</strong><div class="bar"></div><span class="level ${cls}">${level}</span></div>`;}).join('');
  const content=`<div class="results"><div class="result-head"><span class="eyebrow">Founder dependency diagnosis</span><h1>${esc(r.title)}</h1><p>${esc(r.diagnosis)}</p><span class="confidence ${r.confidence}">● ${r.confidence==='strong'?'Strong':r.confidence==='medium'?'Working':'Low'} confidence</span></div><div class="result-grid"><article class="result-card focus"><span class="section-label">Focus first</span><h2>${esc(r.label)}</h2><p>This is the strongest dependency signal in your answers. It is not a claim that every other area is healthy.</p></article><article class="result-card"><span class="section-label">Across the system</span><h3>Dependency levels, not a fake overall percentage</h3><div class="stage-list">${stageRows}</div></article><article class="result-card full"><span class="section-label">Why this showed up</span><h3>Your actual answers</h3>${evidenceItems(r.evidence)}</article><article class="result-card"><span class="section-label">Evidence target</span><h3>What would prove progress</h3><div class="copy-box">${esc(r.evidenceTarget)}</div></article><article class="result-card"><span class="section-label">Candidate first moves</span><h3>Take these into the weekly planner</h3>${actionItems(r.actions)}</article><article class="result-card warning full"><span class="section-label">What this does not prove</span><h3>Use it as a prioritisation hypothesis</h3><p>The result identifies the strongest dependency signal from your answers. Validate it with calls, operating data and team behaviour before making a major investment.</p></article></div>${resultActions(copy,'bottleneck')}${nextCard('Turn this diagnosis into one focused week','The Weekly Focus Planner will compare this result with any other completed tools and create one evidence target with three actions.','/weekly','Use this in the Weekly Focus Planner','bottleneck')}</div>`;
  return layout(content,TOOL_META.bottleneck.title,TOOL_META.bottleneck.desc);
}
