// 2. Customer segment prioritisation
const customerCriteria=[
  {id:'urgency',title:'Problem urgency',q:'How urgently does each segment need the problem solved?',h:'Use recent behaviour, deadlines, consequences and willingness to act.',weight:1.2,labels:['Urgent now','Important, not urgent','Low urgency','Not sure']},
  {id:'evidence',title:'Direct evidence',q:'How much direct customer and revenue evidence do you have?',h:'Recent wins, paid pilots and repeated behaviour matter more than opinions.',weight:1.45,labels:['Repeated paid evidence','Some real evidence','Mostly assumptions','Not sure']},
  {id:'reach',title:'Reachability',q:'How easily can you identify and reach the right buyers?',h:'Consider list quality, existing access, communities, partners and channels.',weight:.9,labels:['Easy to identify and reach','Reachable with effort','Hard to reach','Not sure']},
  {id:'value',title:'Commercial value',q:'How valuable could a good customer in this segment be?',h:'Consider contract value, expansion potential and strategic value.',weight:1.15,labels:['High value','Moderate value','Low value','Not sure']},
  {id:'win',title:'Win rate and sales friction',q:'How likely are qualified opportunities in this segment to convert?',h:'Use actual sales cycles and objections where possible.',weight:1.05,labels:['Converts well','Mixed conversion','Hard to close','Not sure']},
  {id:'retention',title:'Retention and expansion',q:'How well do customers in this segment retain, use and expand?',h:'A segment that buys but does not stay is not a strong priority.',weight:1.25,labels:['Retains and expands','Mostly retains','Weak retention','Not sure']},
  {id:'fit',title:'Delivery fit',q:'How efficiently can your current team serve this segment?',h:'Consider onboarding, custom work, support burden and product fit.',weight:1,labels:['Strong delivery fit','Manageable','High delivery burden','Not sure']}
];
function customerIntro(){return introPage('customer',{label:'Customer segment prioritisation',title:TOOL_META.customer.title,lead:'Compare two or three real segments using evidence, economics, retention and delivery fit. The result recommends a focus while making uncertainty visible.',startFn:'startCustomer',startLabel:completed('customer')?'Review or retake':'Compare my segments',meta:'About 6 minutes · Post-PMF decision logic · No false 91/100 precision',benefits:[['Use real segments','Compare groups you could actually build a list for.'],['Weight evidence properly','Paid behaviour and retention matter more than enthusiasm.'],['Choose and exclude','Leave with a leading segment and a group to deprioritise.']]});}
window.startCustomer=function(){
  const d=state.drafts.customer||{};session={tool:'customer',step:d.step||0,names:d.names||['',''],ratings:d.ratings||customerCriteria.map(()=>[])};track('Tool Started',{tool:'customer'});renderCustomer();
};
window.setSegmentCount=function(count){
  session.names=session.names.slice(0,count);while(session.names.length<count)session.names.push('');persistCustomer();renderCustomer();
};
window.updateSegmentName=function(i,value){session.names[i]=value;persistCustomer();const btn=document.getElementById('segmentContinue');if(btn)btn.disabled=!validSegments();};
function validSegments(){const names=session.names.map(clean);return names.length>=2&&names.every(n=>n.split(' ').length>=3)&&new Set(names.map(n=>n.toLowerCase())).size===names.length;}
function persistCustomer(){state.drafts.customer={step:session.step,names:session.names,ratings:session.ratings};saveState();}
window.customerNamesNext=function(){if(!validSegments())return;session.names=session.names.map(clean);session.step=1;persistCustomer();renderCustomer();window.scrollTo(0,0);};
window.chooseCustomerRating=function(segIndex,value){const ci=session.step-1;if(!session.ratings[ci])session.ratings[ci]=[];session.ratings[ci][segIndex]=value;persistCustomer();renderCustomer();};
window.customerNext=function(){const ci=session.step-1;if(session.ratings[ci]?.length!==session.names.length||session.ratings[ci].some(v=>v===undefined))return;if(session.step<customerCriteria.length){session.step++;persistCustomer();renderCustomer();window.scrollTo(0,0);}else finishCustomer();};
window.customerBack=function(){if(session.step===0){session={};render();}else{session.step--;persistCustomer();renderCustomer();window.scrollTo(0,0);}};
function renderCustomer(){
  if(session.step===0){
    app.innerHTML=layout(`<div class="wizard">${progress(0,customerCriteria.length+1,'Define the segments')}<section class="panel"><span class="step-kicker">Customer options</span><h2>Which segments are you genuinely considering?</h2><p class="intro">Use a specific role or company type, stage and relevant situation. Compare two by default, or add a third when it is a real decision.</p><div class="button-row"><button class="btn ${session.names.length===2?'primary':'secondary'}" onclick="setSegmentCount(2)">Compare 2</button><button class="btn ${session.names.length===3?'primary':'secondary'}" onclick="setSegmentCount(3)">Compare 3</button></div><div class="segment-list">${session.names.map((n,i)=>`<div class="field"><label>Segment ${i+1}</label><input value="${esc(n)}" oninput="updateSegmentName(${i},this.value)" placeholder="e.g. Post-PMF B2B SaaS founders with inconsistent pipeline"><div class="hint">Role or company type + stage + relevant situation.</div></div>`).join('')}</div><div class="quality ${validSegments()?'good':'warn'}">${validSegments()?'These segments are specific enough to compare.':'Each segment needs at least three words and must be meaningfully different.'}</div><div class="wizard-actions"><button class="back" onclick="customerBack()">← Start</button><button id="segmentContinue" class="btn primary" onclick="customerNamesNext()" ${validSegments()?'':'disabled'}>Start comparison →</button></div></section></div>`,TOOL_META.customer.title,TOOL_META.customer.desc);return;
  }
  const ci=session.step-1,c=customerCriteria[ci];const complete=session.ratings[ci]?.length===session.names.length&&!session.ratings[ci].some(v=>v===undefined);
  const rows=session.names.map((n,si)=>`<div class="segment-row"><strong>${esc(n)}</strong><div class="rating-buttons">${c.labels.map((label,i)=>{const value=i===3?null:3-i;const selected=session.ratings[ci]?.[si]===value;return `<button class="rating ${selected?'selected':''}" onclick="chooseCustomerRating(${si},${value===null?'null':value})">${esc(label)}</button>`;}).join('')}</div></div>`).join('');
  app.innerHTML=layout(`<div class="wizard">${progress(session.step,customerCriteria.length+1,c.title)}<section class="panel"><span class="step-kicker">${esc(c.title)}</span><h2>${esc(c.q)}</h2><p class="intro">${esc(c.h)}</p><div class="segment-list">${rows}</div><div class="wizard-actions"><button class="back" onclick="customerBack()">← Back</button><button class="btn primary" onclick="customerNext()" ${complete?'':'disabled'}>${session.step===customerCriteria.length?'See recommendation':'Continue'} →</button></div></section></div>`,TOOL_META.customer.title,TOOL_META.customer.desc);
}
function finishCustomer(){
  const totals=session.names.map(()=>0),known=session.names.map(()=>0),strengths=session.names.map(()=>[]),gaps=session.names.map(()=>[]);
  customerCriteria.forEach((c,ci)=>session.names.forEach((n,si)=>{const v=session.ratings[ci][si];if(v===null){gaps[si].push(c.title);totals[si]+=1*c.weight;}else{totals[si]+=v*c.weight;known[si]++;if(v===3)strengths[si].push(c.title);if(v<=1)gaps[si].push(c.title);}}));
  const ranked=totals.map((score,i)=>({score,i})).sort((a,b)=>b.score-a.score);const top=ranked[0],second=ranked[1];const max=customerCriteria.reduce((s,c)=>s+3*c.weight,0);const gap=(top.score-second.score)/max;const knownRate=known[top.i]/customerCriteria.length;
  const conf=knownRate<.65?'low':gap>.12?'strong':gap>.05?'medium':'low';
  const winner=session.names[top.i],runner=session.names[second.i],deprioritise=session.names[ranked[ranked.length-1].i];
  const weakest=gaps[top.i][0]||'Direct customer evidence';
  const result={winner,runner,deprioritise,confidence:conf,ranked:ranked.map((r,idx)=>({name:session.names[r.i],label:idx===0?'Leading option':idx===1?'Close alternative':'Deprioritise',known:known[r.i],strengths:strengths[r.i],gaps:gaps[r.i]})),evidenceTarget:`Collect one piece of behavioural or revenue evidence that resolves the weakest area for ${winner}: ${weakest}.`,actions:[`Review the last ten wins, losses and active opportunities involving ${winner}.`,`Speak with three recent buyers or customers in ${winner} about the trigger, alternatives and decision criteria.`,`Run one real offer or pipeline test aimed only at ${winner}, then compare qualified response and conversion.`],createdAt:new Date().toISOString()};
  state.results.customer=result;state.profile.customer=winner;delete state.drafts.customer;saveState();track('Tool Completed',{tool:'customer',confidence:conf});session={};render();
}
function customerResult(){
  const r=state.results.customer;if(!r)return customerIntro();
  const copy=`CUSTOMER SEGMENT PRIORITY\n\nLeading option: ${r.winner}\nConfidence: ${r.confidence}\nClose alternative: ${r.runner}\nDeprioritise for now: ${r.deprioritise}\n\nEvidence target\n${r.evidenceTarget}\n\nCandidate validation moves\n${r.actions.map((x,i)=>`${i+1}. ${x}`).join('\n')}`;
  const ranks=r.ranked.map((x,i)=>`<div class="rank-card ${i===0?'top':''}"><h4>${esc(x.name)}</h4><div class="rank-meta"><span class="status ${i===0?'done':'progress'}">${esc(x.label)}</span><span class="chip">${x.known} of ${customerCriteria.length} criteria known</span></div>${x.strengths.length?`<p><strong>Strongest:</strong> ${esc(x.strengths.slice(0,2).join(', '))}</p>`:''}${x.gaps.length?`<p><strong>Needs evidence:</strong> ${esc(x.gaps.slice(0,2).join(', '))}</p>`:''}</div>`).join('');
  const content=`<div class="results"><div class="result-head"><span class="eyebrow">Customer segment priority</span><h1>Prioritise ${esc(r.winner)}.</h1><p>This is the leading option based on the evidence, economics and delivery fit you entered. It is a decision hypothesis, not a permanent ICP definition.</p><span class="confidence ${r.confidence}">● ${r.confidence==='strong'?'Strong':r.confidence==='medium'?'Working':'Low'} confidence</span></div><div class="result-grid"><article class="result-card focus"><span class="section-label">Leading option</span><h2>${esc(r.winner)}</h2><p>Use this as the primary segment for the next controlled messaging, pipeline or offer test.</p></article><article class="result-card"><span class="section-label">Explicit exclusion</span><h3>Deprioritise for now</h3><div class="copy-box">${esc(r.deprioritise)}</div><p>Deprioritising is temporary. Reopen the decision when new evidence changes the economics or fit.</p></article><article class="result-card full"><span class="section-label">Ranked comparison</span><h3>Relative position, without fake precision</h3>${ranks}</article><article class="result-card"><span class="section-label">Evidence target</span><h3>Resolve the weakest assumption</h3><div class="copy-box">${esc(r.evidenceTarget)}</div></article><article class="result-card"><span class="section-label">Candidate validation moves</span><h3>Take these into the weekly planner</h3>${actionItems(r.actions)}</article><article class="result-card warning full"><span class="section-label">What this does not prove</span><h3>A leading segment can still fail in market</h3><p>The result does not prove market size, willingness to pay or repeatable acquisition. It prioritises where to collect the next evidence.</p></article></div>${resultActions(copy,'customer')}${nextCard('Turn the chosen segment into clear messaging','The Positioning Builder is already prefilled with your leading customer segment.','/positioning','Build the message','customer')}</div>`;
  return layout(content,TOOL_META.customer.title,TOOL_META.customer.desc);
}
