// 4. GTM leak diagnostic
const leakStages=[
  {id:'demand',name:'Right-fit demand',desc:'Enough best-fit prospects enter the journey.',metric:'Qualified conversations created per week',actions:{measurement:['Define exactly what counts as a right-fit prospect and qualified conversation.','Instrument the source and qualification status for every new conversation.','Review the last 20 inbound and outbound responses to establish a baseline.'],volume:['Choose the one channel with the strongest evidence and define a protected weekly activity target.','Run one focused message and audience combination for two full weeks.','Review qualified conversations, not impressions or raw leads.'],conversion:['Review 10 recent responses and non-responses to identify message or audience mismatch.','Write one hypothesis about the signal, customer or problem language.','Test one controlled change with a clear response threshold.']}},
  {id:'qualification',name:'Qualification',desc:'The right prospects become real opportunities.',metric:'Qualified opportunity rate',actions:{measurement:['Define the minimum criteria for a qualified opportunity.','Tag the last 20 conversations against those criteria.','Agree one owner and one weekly qualification review.'],volume:['Audit whether the audience and channels produce enough right-fit conversations.','Tighten the customer definition and list criteria.','Run one targeted acquisition test before changing sales process.'],conversion:['Review the last 10 disqualified or stalled conversations.','Identify the most common mismatch in problem, timing, authority or budget.','Change one qualification question or pre-call signal, then compare the next 10.']}},
  {id:'sales',name:'Sales conversion',desc:'Qualified opportunities become paying customers.',metric:'Qualified opportunity to closed-won rate',actions:{measurement:['Define each sales stage and the evidence required to enter it.','Rebuild the last 15 opportunities using the same stage definitions.','Start a weekly loss and stall review.'],volume:['Confirm there are enough qualified opportunities before changing the sales process.','Set a minimum weekly opportunity target.','Protect prospecting capacity while reviewing conversion.'],conversion:['Review five wins, five losses and five stalled deals.','Identify the repeated objection, missing proof or decision friction.','Change one part of the sales narrative or follow-up and test it on the next five opportunities.']}},
  {id:'activation',name:'Activation',desc:'New customers reach meaningful value quickly.',metric:'Time to first meaningful value',actions:{measurement:['Define the first customer behaviour that predicts successful use.','Measure time from purchase to that behaviour for the last 20 customers.','Create a weekly list of customers who have not activated.'],volume:['Confirm enough new customers are entering onboarding to make the signal reliable.','Review onboarding capacity and ownership.','Use qualitative onboarding evidence until the sample is larger.'],conversion:['Interview five customers who activated and five who did not.','Identify the single step where momentum drops.','Remove, simplify or support that step, then compare the next cohort.']}},
  {id:'retention',name:'Retention',desc:'Customers continue receiving value and stay.',metric:'Logo and revenue retention by segment',actions:{measurement:['Choose one retention window and calculate it consistently by customer segment.','Review every churned account from the last six months.','Add a simple customer-risk review with named owners.'],volume:['Confirm the cohort is large enough for meaningful quantitative retention analysis.','Use customer interviews and product behaviour to identify early patterns.','Avoid broad conclusions from a very small sample.'],conversion:['Review churn reasons, usage and support patterns for the last 10 losses.','Identify the earliest observable warning signal.','Run one proactive retention intervention for every account showing that signal.']}},
  {id:'expansion',name:'Expansion and advocacy',desc:'Successful customers grow, renew and refer.',metric:'Expansion revenue and qualified referrals',actions:{measurement:['Define expansion and advocacy events you can record consistently.','Review the last 20 successful customers for missed opportunities.','Add a quarterly customer outcome and expansion review.'],volume:['Confirm enough customers have reached clear value before pushing expansion.','Build a list of customers with proven outcomes.','Focus first on creating success signals, then ask for expansion or advocacy.'],conversion:['Interview successful customers who did and did not expand.','Identify the outcome, trigger and stakeholder that created expansion.','Test one outcome review and relevant next offer with five strong accounts.']}}
];
const leakStatus=[{id:'unknown',label:'Not measured',desc:'We cannot reliably see what happens at this stage.',severity:2.4},{id:'volume',label:'Insufficient volume',desc:'Too few right-fit people or customers reach this stage.',severity:2.6},{id:'conversion',label:'Converting poorly',desc:'Enough reach the stage, but too few progress.',severity:3},{id:'healthy',label:'Mostly healthy',desc:'Performance is understood and broadly acceptable.',severity:.5}];
const impacts=[{id:'high',label:'High commercial impact',mult:1.4},{id:'medium',label:'Moderate impact',mult:1},{id:'low',label:'Lower impact',mult:.6}];
function leakIntro(){return introPage('leak',{label:'GTM leak diagnostic',title:TOOL_META.leak.title,lead:'Separate volume, conversion and measurement problems across six stages, then identify the stage with the greatest likely commercial impact.',startFn:'startLeak',startLabel:completed('leak')?'Review or retake':'Diagnose the journey',meta:'About 5 minutes · 6 stages · Missing measurement is treated as its own constraint',benefits:[['Name the failure type','Do not confuse low volume with poor conversion.'],['Weight commercial impact','The weakest-looking stage is not always the most important.'],['Choose one evidence target','The result moves directly into the Weekly Focus Planner.']]});}
window.startLeak=function(){const d=state.drafts.leak||{};session={tool:'leak',step:d.step||0,answers:d.answers||leakStages.map(()=>({status:null,impact:null}))};track('Tool Started',{tool:'leak'});renderLeak();};
function persistLeak(){state.drafts.leak={step:session.step,answers:session.answers};saveState();}
window.chooseLeakStatus=function(id){session.answers[session.step].status=id;persistLeak();renderLeak();};
window.chooseLeakImpact=function(id){session.answers[session.step].impact=id;persistLeak();renderLeak();};
window.leakNext=function(){const a=session.answers[session.step];if(!a.status||!a.impact)return;if(session.step<leakStages.length-1){session.step++;persistLeak();renderLeak();window.scrollTo(0,0);}else finishLeak();};
window.leakBack=function(){if(session.step===0){session={};render();}else{session.step--;persistLeak();renderLeak();window.scrollTo(0,0);}};
function renderLeak(){
  const s=leakStages[session.step],a=session.answers[session.step];
  app.innerHTML=layout(`<div class="wizard">${progress(session.step,leakStages.length,s.name)}<section class="panel"><span class="step-kicker">${esc(s.name)}</span><h2>What is happening at this stage?</h2><p class="intro">${esc(s.desc)}</p><div class="options">${leakStatus.map((o,i)=>`<button type="button" class="option ${a.status===o.id?'selected':''}" onclick="chooseLeakStatus('${o.id}')"><span class="option-mark">${String.fromCharCode(65+i)}</span><span><strong>${esc(o.label)}</strong><span class="desc">${esc(o.desc)}</span></span></button>`).join('')}</div><h3 style="margin-top:28px">How commercially important is this stage right now?</h3><div class="rating-buttons">${impacts.map(i=>`<button class="rating ${a.impact===i.id?'selected':''}" onclick="chooseLeakImpact('${i.id}')">${esc(i.label)}</button>`).join('')}</div><div class="wizard-actions"><button class="back" onclick="leakBack()">← ${session.step===0?'Start':'Back'}</button><button class="btn primary" onclick="leakNext()" ${a.status&&a.impact?'':'disabled'}>${session.step===leakStages.length-1?'See diagnosis':'Continue'} →</button></div></section></div>`,TOOL_META.leak.title,TOOL_META.leak.desc);
}
function finishLeak(){
  const scored=session.answers.map((a,i)=>{const status=leakStatus.find(x=>x.id===a.status),impact=impacts.find(x=>x.id===a.impact);return{score:status.severity*impact.mult,i,status,impact};}).sort((a,b)=>b.score-a.score);
  const top=scored[0],second=scored[1],stage=leakStages[top.i];const gap=top.score-second.score;const unknowns=session.answers.filter(a=>a.status==='unknown').length;
  const conf=unknowns>=3?'low':gap>=.8?'strong':gap>=.3?'medium':'low';
  const type=top.status.id==='unknown'?'Measurement gap':top.status.id==='volume'?'Volume constraint':top.status.id==='conversion'?'Conversion leak':'Lowest-priority healthy stage';
  const evidenceTarget=top.status.id==='unknown'?`Establish a reliable baseline for ${stage.metric.toLowerCase()} and review it by customer segment.`:top.status.id==='volume'?`Create enough right-fit volume at ${stage.name.toLowerCase()} to judge performance using ${stage.metric.toLowerCase()}.`:`Improve ${stage.metric.toLowerCase()} through one controlled change, with the current baseline recorded before the test.`;
  const actions=stage.actions[top.status.id==='healthy'?'measurement':top.status.id];
  const result={stageId:stage.id,stage:stage.name,type,status:top.status.id,impact:top.impact.id,confidence:conf,diagnosis:`The strongest current signal is a ${type.toLowerCase()} at ${stage.name.toLowerCase()}. ${top.status.desc}`,metric:stage.metric,evidenceTarget,actions,stages:session.answers.map((a,i)=>({name:leakStages[i].name,status:leakStatus.find(x=>x.id===a.status).label,impact:impacts.find(x=>x.id===a.impact).label,id:a.status})),createdAt:new Date().toISOString()};
  state.results.leak=result;delete state.drafts.leak;saveState();track('Tool Completed',{tool:'leak',stage:stage.id,type:top.status.id});session={};render();
}
function leakResult(){
  const r=state.results.leak;if(!r)return leakIntro();
  const copy=`GTM LEAK DIAGNOSIS\n\nFocus: ${r.type} at ${r.stage}\nConfidence: ${r.confidence}\n\nDiagnosis\n${r.diagnosis}\n\nMetric\n${r.metric}\n\nEvidence target\n${r.evidenceTarget}\n\nCandidate first moves\n${r.actions.map((x,i)=>`${i+1}. ${x}`).join('\n')}`;
  const rows=r.stages.map(s=>{const cls=s.id==='conversion'?'high':s.id==='volume'?'mixed':s.id==='unknown'?'unknown':'good';return `<div class="stage-row"><strong>${esc(s.name)}</strong><span>${esc(s.impact)}</span><span class="level ${cls}">${esc(s.status)}</span></div>`;}).join('');
  const content=`<div class="results"><div class="result-head"><span class="eyebrow">GTM leak diagnosis</span><h1>${esc(r.type)} at ${esc(r.stage)}.</h1><p>${esc(r.diagnosis)}</p><span class="confidence ${r.confidence}">● ${r.confidence==='strong'?'Strong':r.confidence==='medium'?'Working':'Low'} confidence</span></div><div class="result-grid"><article class="result-card focus"><span class="section-label">Focus stage</span><h2>${esc(r.stage)}</h2><span class="level ${r.status==='conversion'?'high':r.status==='volume'?'mixed':r.status==='unknown'?'unknown':'good'}">${esc(r.type)}</span><p>${esc(r.diagnosis)}</p></article><article class="result-card"><span class="section-label">Primary measure</span><h3>${esc(r.metric)}</h3><p>Record the current baseline before changing activity, messaging or process.</p></article><article class="result-card full"><span class="section-label">Across the journey</span><h3>Failure type and commercial importance</h3><div class="stage-list">${rows}</div></article><article class="result-card"><span class="section-label">Evidence target</span><h3>What to learn next</h3><div class="copy-box">${esc(r.evidenceTarget)}</div></article><article class="result-card"><span class="section-label">Candidate first moves</span><h3>Take these into the weekly planner</h3>${actionItems(r.actions)}</article><article class="result-card warning full"><span class="section-label">What this does not prove</span><h3>The most visible leak may have an upstream cause</h3><p>For example, weak sales conversion can begin with the wrong segment or unclear positioning. Use the recommended metric and customer evidence to confirm the cause before rebuilding the whole journey.</p></article></div>${resultActions(copy,'leak')}${nextCard('Choose the single constraint for this week','The Weekly Focus Planner will compare this diagnosis with the other completed tools, then generate one evidence target and three time-boxed actions.','/weekly','Build the weekly plan','leak')}</div>`;
  return layout(content,TOOL_META.leak.title,TOOL_META.leak.desc);
}
