// 3. Positioning builder
const positioningFields=[
  {key:'product',title:'Name the product',q:'What is the product or service called?',hint:'Use the name a customer would recognise.',placeholder:'Crux',min:2,example:'Crux'},
  {key:'customer',title:'Choose the customer',q:'Who exactly is this message for?',hint:'Use a plural customer group, with role or company type, stage and situation.',placeholder:'Post-PMF B2B SaaS founders with inconsistent pipeline',min:5,example:'Post-PMF B2B SaaS and AI founders with inconsistent pipeline'},
  {key:'trigger',title:'Name the trigger',q:'What is happening when they start looking for help?',hint:'Write a clause without “when”, for example: pipeline becomes unpredictable despite more activity.',placeholder:'pipeline becomes unpredictable despite more activity',min:6,example:'pipeline becomes unpredictable even though the team is running more campaigns'},
  {key:'problem',title:'Name the problem',q:'What problem are they facing?',hint:'Use a noun phrase, for example: difficulty identifying the real commercial constraint.',placeholder:'difficulty identifying the real commercial constraint',min:5,example:'difficulty identifying the real commercial constraint holding back pipeline'},
  {key:'consequence',title:'Show the cost',q:'What happens if the problem remains unsolved?',hint:'Write a complete sentence about revenue, cost, risk, delay or founder dependency.',placeholder:'They waste budget and team time on disconnected activity.',min:7,example:'They waste budget and team time on disconnected activity while the founder remains the decision bottleneck.'},
  {key:'outcome',title:'Define the outcome',q:'What should the customer be able to do?',hint:'Start with an action verb. This becomes the headline, for example: Build a predictable pipeline without founder heroics.',placeholder:'Build a predictable pipeline without founder heroics',min:5,example:'Find the real constraint and build a repeatable growth rhythm'},
  {key:'alternative',title:'Name the alternative',q:'What do they use or do instead today?',hint:'Use a noun phrase, for example: founder intuition, broad agency retainers or disconnected campaigns.',placeholder:'founder intuition and disconnected campaigns',min:4,example:'founder intuition, broad strategy decks and disconnected campaigns'},
  {key:'mechanism',title:'Explain the difference',q:'How does your approach create the outcome?',hint:'Start with an “-ing” word, “using” or “combining”, for example: diagnosing the constraint before recommending activity.',placeholder:'diagnosing the constraint before recommending activity',min:5,example:'diagnosing the constraint first, running controlled tests and transferring the system into the team'},
  {key:'proof',title:'Add evidence',q:'What evidence supports the direction?',hint:'Metrics, case studies and repeated customer behaviour are stronger than general praise. This can be left blank.',placeholder:'£18M+ revenue influenced and repeated founder evidence across 479+ sessions',min:0,example:'£18M+ revenue influenced, £6M+ acquisition spend managed and repeated founder evidence across 479+ sessions'}
];
const vagueWords=['innovative','seamless','revolutionary','best-in-class','world-class','empower','unlock','transform','all-in-one','cutting-edge','ai-powered','powerful solution'];
function positioningIntro(){return introPage('positioning',{label:'Positioning and messaging builder',title:TOOL_META.positioning.title,lead:'Make the positioning choices first, then generate four focused outputs with a visible quality check and editable copy.',startFn:'startPositioning',exampleFn:'examplePositioning',startLabel:completed('positioning')?'Review or retake':'Build my messaging',meta:'About 8 minutes · Four useful outputs · Editable before copying',benefits:[['One strategic direction','No ten-variant AI copy dump.'],['Grammar-safe inputs','Each question asks for a phrase that fits the final structure.'],['Visible quality check','Generic wording, weak evidence and excessive length are flagged.']]});}
window.startPositioning=function(){
  const prefill={product:state.profile.product||'',customer:state.profile.customer||''};const saved=state.drafts.positioning?.answers||{};session={tool:'positioning',step:0,answers:{...prefill,...saved}};track('Tool Started',{tool:'positioning'});renderPositioning();
};
window.examplePositioning=function(){session={tool:'positioning',step:0,answers:Object.fromEntries(positioningFields.map(f=>[f.key,f.example]))};state.drafts.positioning={answers:session.answers};saveState();track('Tool Started',{tool:'positioning',source:'example'});renderPositioning();};
function positioningQuality(field,value){
  const v=clean(value);if(!v&&field.min===0)return{ok:true,kind:'warn',text:'Optional. Leaving this blank will make the claims a lower-confidence hypothesis.'};
  if(v.length<field.min)return{ok:false,kind:'bad',text:'Add a little more detail so the output can be specific.'};
  const vague=vagueWords.find(w=>v.toLowerCase().includes(w));if(vague)return{ok:false,kind:'bad',text:`“${vague}” is difficult to picture. Replace it with what changes in practice.`};
  if(field.key==='customer'&&v.split(' ').length<4)return{ok:false,kind:'bad',text:'Add a role or company type, stage and relevant situation.'};
  if(field.key==='trigger'&&/^when\b/i.test(v))return{ok:false,kind:'bad',text:'Remove “when”. The final copy adds it for you.'};
  if(field.key==='problem'&&/^(they|we|it)\b/i.test(v))return{ok:false,kind:'bad',text:'Use a noun phrase rather than a full sentence, for example: difficulty identifying the real constraint.'};
  if(field.key==='outcome'&&/^(to|we|they|customers?)\b/i.test(v))return{ok:false,kind:'bad',text:'Start with an action verb, for example: Build, Find, Reduce or Create.'};
  if(field.key==='mechanism'&&!/^(using|combining|diagnosing|identifying|analysing|analyzing|testing|connecting|mapping|reviewing|building|turning|capturing|automating|prioritising|prioritizing|measuring|matching|integrating|creating|providing|replacing|transferring|running)\b/i.test(v))return{ok:false,kind:'warn',text:'Start with an “-ing” action so the final sentence reads naturally.'};
  if(v.split(' ').length>28)return{ok:false,kind:'warn',text:'Shorten this to one idea. Long inputs create weak messaging.'};
  return{ok:true,kind:'good',text:'Specific enough to use in the working direction.'};
}
window.updatePositioning=function(value){const f=positioningFields[session.step];session.answers[f.key]=value;state.drafts.positioning={answers:session.answers};saveState();const q=positioningQuality(f,value);const el=document.getElementById('positionQuality');if(el){el.className=`quality ${q.kind}`;el.textContent=q.text;}const btn=document.getElementById('positionNext');if(btn)btn.disabled=!q.ok;};
window.positionNext=function(){const f=positioningFields[session.step],q=positioningQuality(f,session.answers[f.key]||'');if(!q.ok)return;session.answers[f.key]=clean(session.answers[f.key]);if(session.step<positioningFields.length-1){session.step++;renderPositioning();window.scrollTo(0,0);}else renderPositionReview();};
window.positionBack=function(){if(session.step===0){session={};render();}else{session.step--;renderPositioning();window.scrollTo(0,0);}};
function renderPositioning(){
  const f=positioningFields[session.step],v=session.answers[f.key]||'',q=positioningQuality(f,v);
  app.innerHTML=layout(`<div class="wizard">${progress(session.step,positioningFields.length,f.title)}<section class="panel"><span class="step-kicker">${esc(f.title)}</span><h2>${esc(f.q)}</h2><p class="intro">${esc(f.hint)}</p><div class="field"><label>Your answer</label><textarea autofocus oninput="updatePositioning(this.value)" placeholder="${esc(f.placeholder)}">${esc(v)}</textarea><div id="positionQuality" class="quality ${q.kind}">${esc(q.text)}</div></div><details style="margin-top:14px"><summary class="micro">See a useful example</summary><p>${esc(f.example)}</p></details><div class="wizard-actions"><button class="back" onclick="positionBack()">← ${session.step===0?'Start':'Back'}</button><button id="positionNext" class="btn primary" onclick="positionNext()" ${q.ok?'':'disabled'}>${session.step===positioningFields.length-1?'Review direction':'Continue'} →</button></div></section></div>`,TOOL_META.positioning.title,TOOL_META.positioning.desc);
}
function renderPositionReview(){
  app.innerHTML=layout(`<div class="wizard">${progress(positioningFields.length-1,positioningFields.length,'Review the choices')}<section class="panel"><span class="step-kicker">Before the copy</span><h2>Is this the direction you want to test?</h2><p class="intro">The output will only be as strong as these strategic choices.</p><div class="review-list">${positioningFields.map(f=>`<div class="review-row"><span>${esc(f.title)}</span><strong>${esc(session.answers[f.key]||'Not provided')}</strong></div>`).join('')}</div><div class="wizard-actions"><button class="back" onclick="session.step=${positioningFields.length-1};renderPositioning()">← Edit</button><button class="btn primary" onclick="finishPositioning()">Generate messaging →</button></div></section></div>`,TOOL_META.positioning.title,TOOL_META.positioning.desc);
}
window.finishPositioning=function(){
  const a=Object.fromEntries(Object.entries(session.answers).map(([k,v])=>[k,clean(v)]));
  const headline=sentence(a.outcome);
  const subheadline=`${a.product} helps ${a.customer} ${lowerFirst(a.outcome)} by ${lowerFirst(a.mechanism)}.`;
  const oneLine=subheadline;
  const problemStatement=`When ${lowerFirst(a.trigger)}, ${a.customer} face ${lowerFirst(a.problem)}. ${sentence(a.consequence)}`;
  const salesIntro=`We work with ${a.customer} when ${lowerFirst(a.trigger)}. ${a.product} helps them ${lowerFirst(a.outcome)} by ${lowerFirst(a.mechanism)}.`;
  const outreach=`I noticed ${lowerFirst(a.trigger)} is a common issue for ${a.customer}. We help teams ${lowerFirst(a.outcome)}. Open to comparing notes?`;
  const differentiation=`Instead of ${lowerFirst(a.alternative)}, ${a.product} works by ${lowerFirst(a.mechanism)}.`;
  const issues=[];
  if(headline.length>80)issues.push('The headline is long. Aim for fewer than 80 characters.');
  if(subheadline.length>220)issues.push('The subheadline is long. Remove one idea before publishing.');
  if(!a.proof)issues.push('No proof was supplied. Treat the outcome and differentiation as hypotheses.');
  if(vagueWords.some(w=>(headline+' '+subheadline).toLowerCase().includes(w)))issues.push('Generic language remains in the output. Replace it with an observable result.');
  const conf=a.proof&&/[0-9£$%+]/.test(a.proof)?'strong':a.proof?'medium':'low';
  const result={...a,headline,subheadline,oneLine,problemStatement,salesIntro,outreach,differentiation,issues,confidence:conf,evidenceTarget:`Show the headline and subheadline to five people in ${a.customer}. Keep the direction only if they can explain what ${a.product} does, who it is for and why it matters without additional explanation.`,actions:[`Show the hero message to five target customers without explaining it.`,`Record the exact words they use to describe the problem and outcome.`,`Test the outreach opener with 20 carefully selected prospects and compare qualified responses.`],createdAt:new Date().toISOString()};
  state.results.positioning=result;state.profile.product=a.product;state.profile.customer=a.customer;delete state.drafts.positioning;saveState();track('Tool Completed',{tool:'positioning',confidence:conf});session={};render();
};
window.editOutput=function(key,value){state.results.positioning[key]=value;saveState();};
function outputBlock(label,key,value){return `<article class="result-card"><span class="section-label">${esc(label)}</span><div class="output-row"><textarea class="editable-output" oninput="editOutput('${key}',this.value)">${esc(value)}</textarea><button class="copy-small" onclick="copyText(state.results.positioning['${key}'])">Copy</button></div></article>`;}
function positioningResult(){
  const r=state.results.positioning;if(!r)return positioningIntro();
  const copy=`WORKING POSITIONING DIRECTION\n\nHOMEPAGE HEADLINE\n${r.headline}\n\nHOMEPAGE SUBHEADLINE\n${r.subheadline}\n\nSALES INTRODUCTION\n${r.salesIntro}\n\nOUTREACH OPENER\n${r.outreach}\n\nPROBLEM STATEMENT\n${r.problemStatement}\n\nDIFFERENTIATION\n${r.differentiation}\n\nEVIDENCE\n${r.proof||'No evidence supplied'}\n\nCUSTOMER TEST\n${r.evidenceTarget}`;
  const content=`<div class="results"><div class="result-head"><span class="eyebrow">Working messaging direction</span><h1>${esc(r.headline)}</h1><p>These are editable working drafts. Test whether customers understand them before publishing or scaling.</p><span class="confidence ${r.confidence}">● ${r.confidence==='strong'?'Stronger evidence':r.confidence==='medium'?'Working hypothesis':'Low evidence'}</span></div><div class="result-grid"><article class="result-card focus full"><span class="section-label">Positioning foundation</span><div class="summary-grid"><div class="summary-card"><span>For</span><strong>${esc(r.customer)}</strong></div><div class="summary-card"><span>Outcome</span><strong>${esc(r.outcome)}</strong></div><div class="summary-card"><span>Mechanism</span><strong>${esc(r.mechanism)}</strong></div></div></article>${outputBlock('Homepage headline','headline',r.headline)}${outputBlock('Homepage subheadline','subheadline',r.subheadline)}${outputBlock('Sales introduction','salesIntro',r.salesIntro)}${outputBlock('Outreach opener','outreach',r.outreach)}<article class="result-card"><span class="section-label">Problem statement</span><div class="copy-box">${esc(r.problemStatement)}</div><button class="copy-small" style="margin-top:8px" onclick="copyText(state.results.positioning.problemStatement)">Copy</button></article><article class="result-card"><span class="section-label">Differentiation</span><div class="copy-box">${esc(r.differentiation)}</div><button class="copy-small" style="margin-top:8px" onclick="copyText(state.results.positioning.differentiation)">Copy</button></article><article class="result-card ${r.issues.length?'warning':''} full"><span class="section-label">Quality check</span><h3>${r.issues.length?'Resolve these before publishing':'The draft passes the current structural checks'}</h3>${r.issues.length?evidenceItems(r.issues):'<p>The inputs are specific, the sentence structures are complete and the main claims are supported by evidence. Customer testing is still required.</p>'}</article><article class="result-card"><span class="section-label">Evidence behind it</span><h3>${r.proof?'Proof supplied':'No proof supplied'}</h3><p>${esc(r.proof||'Keep the outcome and differentiation framed as hypotheses until you have customer behaviour or results to support them.')}</p></article><article class="result-card"><span class="section-label">Customer test</span><h3>Validate understanding, not applause</h3><div class="copy-box">${esc(r.evidenceTarget)}</div></article></div>${resultActions(copy,'positioning')}${nextCard('Find where the customer journey is leaking','Use the GTM Leak Diagnostic to see whether the message, pipeline, conversion, activation or retention is the most important constraint.','/leak','Diagnose the customer journey','positioning')}</div>`;
  return layout(content,TOOL_META.positioning.title,TOOL_META.positioning.desc);
}
